function [ constraintvalue, j_constraintvalue ] = mb_fm_mex_tracklimits( outputs, states, controls )
%mb_fm_mex_tracklimits
% File automatically generated by FALCON.m

%=== Extract Data From Input ==============================================
n_wheel = outputs(1);
M_wheel = outputs(2);
a_r = outputs(3);
a_f = outputs(4);
t = states(1);
v = states(2);
psi_dot = states(3);
beta = states(4);
n = states(5);
xi = states(6);
objective = states(7);
delta = states(8);
delta_dot = controls(1);
fB = controls(2);
zeta = controls(3);
phi = controls(4);
C = controls(5);
nCurbLeft = controls(6);
nCurbRight = controls(7);

%=== Jacobians and Hessians ===============================================
j_n_wheel = zeros(1,19);
j_n_wheel(:,1) = eye(1);
j_M_wheel = zeros(1,19);
j_M_wheel(:,2) = eye(1);
j_a_r = zeros(1,19);
j_a_r(:,3) = eye(1);
j_a_f = zeros(1,19);
j_a_f(:,4) = eye(1);
j_t = zeros(1,19);
j_t(:,5) = eye(1);
j_v = zeros(1,19);
j_v(:,6) = eye(1);
j_psi_dot = zeros(1,19);
j_psi_dot(:,7) = eye(1);
j_beta = zeros(1,19);
j_beta(:,8) = eye(1);
j_n = zeros(1,19);
j_n(:,9) = eye(1);
j_xi = zeros(1,19);
j_xi(:,10) = eye(1);
j_objective = zeros(1,19);
j_objective(:,11) = eye(1);
j_delta = zeros(1,19);
j_delta(:,12) = eye(1);
j_delta_dot = zeros(1,19);
j_delta_dot(:,13) = eye(1);
j_fB = zeros(1,19);
j_fB(:,14) = eye(1);
j_zeta = zeros(1,19);
j_zeta(:,15) = eye(1);
j_phi = zeros(1,19);
j_phi(:,16) = eye(1);
j_C = zeros(1,19);
j_C(:,17) = eye(1);
j_nCurbLeft = zeros(1,19);
j_nCurbLeft(:,18) = eye(1);
j_nCurbRight = zeros(1,19);
j_nCurbRight(:,19) = eye(1);

% Combine Variables to outputs
outputs = [n_wheel; M_wheel; a_r; a_f];
j_outputs = [j_n_wheel(1,:); j_M_wheel(1,:); j_a_r(1,:); j_a_f(1,:)];

% Combine Variables to states
states = [t; v; psi_dot; beta; n; xi; objective; delta];
j_states = [j_t(1,:); j_v(1,:); j_psi_dot(1,:); j_beta(1,:); j_n(1,:); j_xi(1,:); j_objective(1,:); j_delta(1,:)];

% Combine Variables to controls
controls = [delta_dot; fB; zeta; phi; C; nCurbLeft; nCurbRight];
j_controls = [j_delta_dot(1,:); j_fB(1,:); j_zeta(1,:); j_phi(1,:); j_C(1,:); j_nCurbLeft(1,:); j_nCurbRight(1,:)];

%=== Write Constants ======================================================

%=== Call tpae0fcf33_9608_4636_96c4_6aa4549f9ab7 ==========================
[constraintvaluetmp, j_constraintvaluetmp] = tpae0fcf33_9608_4636_96c4_6aa4549f9ab7(outputs, states, controls);

% Hessian Jacobian for tpae0fcf33_9608_4636_96c4_6aa4549f9ab7
tmp_j_input_tpae0fcf33_9608_4636_96c4_6aa4549f9ab7 = [j_outputs; j_states; j_controls];

% Calculation of Jacobian with respect to function global input for tpae0fcf33_9608_4636_96c4_6aa4549f9ab7
j_constraintvaluetmp = j_constraintvaluetmp * tmp_j_input_tpae0fcf33_9608_4636_96c4_6aa4549f9ab7;

% Combine Variables to constraintvalue
constraintvalue = [constraintvaluetmp];
j_constraintvalue = [j_constraintvaluetmp(1,:)];

end
