function [out1,out2,out3] = tp1ffa0651_99a6_48aa_9a46_8713ce66ed32(in1,in2,in3)
%TP1FFA0651_99A6_48AA_9A46_8713CE66ED32
%    [OUT1,OUT2,OUT3] = TP1FFA0651_99A6_48AA_9A46_8713CE66ED32(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Jun-2020 11:52:18

in2val5 = in2(5,:);
in3val6 = in3(6,:);
in3val7 = in3(7,:);
out1 = in2val5+in3val6-in3val7;
if nargout > 1
    out2 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,-1.0];
end
if nargout > 2
    out3 = zeros(0,0);
end

end
