function [out1,out2,out3] = tp20c44840_0d14_4170_a5a8_bdc9bd9a95f6(in1,in2,in3)
%TP20C44840_0D14_4170_A5A8_BDC9BD9A95F6
%    [OUT1,OUT2,OUT3] = TP20C44840_0D14_4170_A5A8_BDC9BD9A95F6(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Jun-2020 11:42:59

in2val5 = in2(5,:);
in3val6 = in3(6,:);
in3val7 = in3(7,:);
out1 = [in2val5+in3val6;in2val5;in3val7];
if nargout > 1
    out2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[3,19]);
end
if nargout > 2
    out3 = zeros(0,0);
end

end
