function [out1,out2,out3] = tp357f86d7_5a41_4a48_8bff_115c50836ecb(in1,in2,in3)
%TP357F86D7_5A41_4A48_8BFF_115C50836ECB
%    [OUT1,OUT2,OUT3] = TP357F86D7_5A41_4A48_8BFF_115C50836ECB(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Jun-2020 12:54:49

in2val5 = in2(5,:);
in3val6 = in3(6,:);
in3val7 = in3(7,:);
out1 = in2val5-in3val6+in3val7;
if nargout > 1
    out2 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0];
end
if nargout > 2
    out3 = zeros(0,0);
end

end
