function [out1,out2,out3] = tp38d8033a_7dcb_444e_91d2_7416958b21de(in1,in2,in3)
%TP38D8033A_7DCB_444E_91D2_7416958B21DE
%    [OUT1,OUT2,OUT3] = TP38D8033A_7DCB_444E_91D2_7416958B21DE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Jun-2020 11:26:39

in2val5 = in2(5,:);
out1 = [in2val5;in2val5];
if nargout > 1
    out2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,19]);
end
if nargout > 2
    out3 = zeros(0,0);
end

end
