function [out1,out2,out3] = tp64ef7d68_3baa_4bd1_a168_07360a26ec92(in1,in2,in3)
%TP64EF7D68_3BAA_4BD1_A168_07360A26EC92
%    [OUT1,OUT2,OUT3] = TP64EF7D68_3BAA_4BD1_A168_07360A26EC92(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Jun-2020 11:23:09

in2val5 = in2(5,:);
in3val6 = in3(6,:);
out1 = in2val5-in3val6;
if nargout > 1
    out2 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0];
end
if nargout > 2
    out3 = zeros(0,0);
end

end
