function [out1,out2,out3] = tp81006514_163d_4178_872f_a02db29c1fc4(in1,in2,in3)
%TP81006514_163D_4178_872F_A02DB29C1FC4
%    [OUT1,OUT2,OUT3] = TP81006514_163D_4178_872F_A02DB29C1FC4(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Jun-2020 11:43:38

in2val5 = in2(5,:);
in3val6 = in3(6,:);
in3val7 = in3(7,:);
out1 = [in2val5+in3val6;in2val5-in3val7];
if nargout > 1
    out2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.0],[2,19]);
end
if nargout > 2
    out3 = zeros(0,0);
end

end
