function [out1,out2,out3] = tpae0fcf33_9608_4636_96c4_6aa4549f9ab7(in1,in2,in3)
%TPAE0FCF33_9608_4636_96C4_6AA4549F9AB7
%    [OUT1,OUT2,OUT3] = TPAE0FCF33_9608_4636_96C4_6AA4549F9AB7(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Jun-2020 13:12:30

in2val5 = in2(5,:);
in3val6 = in3(6,:);
in3val7 = in3(7,:);
out1 = in2val5+in3val6-in3val7;
if nargout > 1
    out2 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,-1.0];
end
if nargout > 2
    out3 = zeros(0,0);
end

end
