function [out1,out2,out3] = tpf9fe25e2_e030_4be8_964b_8997107540fb(in1,in2,in3)
%TPF9FE25E2_E030_4BE8_964B_8997107540FB
%    [OUT1,OUT2,OUT3] = TPF9FE25E2_E030_4BE8_964B_8997107540FB(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Jun-2020 11:24:47

in2val5 = in2(5,:);
in3val6 = in3(6,:);
in3val7 = in3(7,:);
out1 = [in2val5-in3val6;in2val5+in3val7];
if nargout > 1
    out2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,1.0],[2,19]);
end
if nargout > 2
    out3 = zeros(0,0);
end

end
