function [ statesdot, j_statesdot ] = mb_vehicle_nlp( states, controls )
%mb_vehicle_nlp
% File automatically generated by FALCON.m

%=== Extract Data From Input ==============================================
t = states(1);
v = states(2);
psi_dot = states(3);
beta = states(4);
n = states(5);
xi = states(6);
delta = controls(1);
fB = controls(2);
zeta = controls(3);
phi = controls(4);
C = controls(5);

%=== Jacobians and Hessians ===============================================
j_t = zeros(1,11);
j_t(:,1) = eye(1);
j_v = zeros(1,11);
j_v(:,2) = eye(1);
j_psi_dot = zeros(1,11);
j_psi_dot(:,3) = eye(1);
j_beta = zeros(1,11);
j_beta(:,4) = eye(1);
j_n = zeros(1,11);
j_n(:,5) = eye(1);
j_xi = zeros(1,11);
j_xi(:,6) = eye(1);
j_delta = zeros(1,11);
j_delta(:,7) = eye(1);
j_fB = zeros(1,11);
j_fB(:,8) = eye(1);
j_zeta = zeros(1,11);
j_zeta(:,9) = eye(1);
j_phi = zeros(1,11);
j_phi(:,10) = eye(1);
j_C = zeros(1,11);
j_C(:,11) = eye(1);

% Combine Variables to states
states = [t; v; psi_dot; beta; n; xi];
j_states = [j_t(1,:); j_v(1,:); j_psi_dot(1,:); j_beta(1,:); j_n(1,:); j_xi(1,:)];

% Combine Variables to controls
controls = [delta; fB; zeta; phi; C];
j_controls = [j_delta(1,:); j_fB(1,:); j_zeta(1,:); j_phi(1,:); j_C(1,:)];

%=== Write Constants ======================================================

%=== Call tpd459cfc5_dac7_4ebd_934b_0d725fb917cf ==========================
[v_dot, beta_dot, psi_dot_dot, j_v_dot, j_beta_dot, j_psi_dot_dot] = tpd459cfc5_dac7_4ebd_934b_0d725fb917cf(v, beta, psi_dot, delta, fB, zeta, phi);

% Hessian Jacobian for tpd459cfc5_dac7_4ebd_934b_0d725fb917cf
tmp_j_input_tpd459cfc5_dac7_4ebd_934b_0d725fb917cf = [j_v; j_beta; j_psi_dot; j_delta; j_fB; j_zeta; j_phi];

% Calculation of Jacobian with respect to function global input for tpd459cfc5_dac7_4ebd_934b_0d725fb917cf
j_v_dot = j_v_dot * tmp_j_input_tpd459cfc5_dac7_4ebd_934b_0d725fb917cf;
j_beta_dot = j_beta_dot * tmp_j_input_tpd459cfc5_dac7_4ebd_934b_0d725fb917cf;
j_psi_dot_dot = j_psi_dot_dot * tmp_j_input_tpd459cfc5_dac7_4ebd_934b_0d725fb917cf;

%=== Call tpbe88c1b2_64dd_4786_862f_71e4428e1e5e ==========================
[s_dot, n_dot, xi_dot, j_s_dot, j_n_dot, j_xi_dot] = tpbe88c1b2_64dd_4786_862f_71e4428e1e5e(psi_dot, v, beta, n, xi, C);

% Hessian Jacobian for tpbe88c1b2_64dd_4786_862f_71e4428e1e5e
tmp_j_input_tpbe88c1b2_64dd_4786_862f_71e4428e1e5e = [j_psi_dot; j_v; j_beta; j_n; j_xi; j_C];

% Calculation of Jacobian with respect to function global input for tpbe88c1b2_64dd_4786_862f_71e4428e1e5e
j_s_dot = j_s_dot * tmp_j_input_tpbe88c1b2_64dd_4786_862f_71e4428e1e5e;
j_n_dot = j_n_dot * tmp_j_input_tpbe88c1b2_64dd_4786_862f_71e4428e1e5e;
j_xi_dot = j_xi_dot * tmp_j_input_tpbe88c1b2_64dd_4786_862f_71e4428e1e5e;

%=== Call tpbd853070_1cee_4fb6_afc0_551a36750e15 ==========================
[t_dot_s, v_dot_s, psi_dot_dot_s, beta_dot_s, n_dot_s, xi_dot_s, j_t_dot_s, j_v_dot_s, j_psi_dot_dot_s, j_beta_dot_s, j_n_dot_s, j_xi_dot_s] = tpbd853070_1cee_4fb6_afc0_551a36750e15(v_dot, psi_dot_dot, beta_dot, n_dot, xi_dot, s_dot);

% Hessian Jacobian for tpbd853070_1cee_4fb6_afc0_551a36750e15
tmp_j_input_tpbd853070_1cee_4fb6_afc0_551a36750e15 = [j_v_dot; j_psi_dot_dot; j_beta_dot; j_n_dot; j_xi_dot; j_s_dot];

% Calculation of Jacobian with respect to function global input for tpbd853070_1cee_4fb6_afc0_551a36750e15
j_t_dot_s = j_t_dot_s * tmp_j_input_tpbd853070_1cee_4fb6_afc0_551a36750e15;
j_v_dot_s = j_v_dot_s * tmp_j_input_tpbd853070_1cee_4fb6_afc0_551a36750e15;
j_psi_dot_dot_s = j_psi_dot_dot_s * tmp_j_input_tpbd853070_1cee_4fb6_afc0_551a36750e15;
j_beta_dot_s = j_beta_dot_s * tmp_j_input_tpbd853070_1cee_4fb6_afc0_551a36750e15;
j_n_dot_s = j_n_dot_s * tmp_j_input_tpbd853070_1cee_4fb6_afc0_551a36750e15;
j_xi_dot_s = j_xi_dot_s * tmp_j_input_tpbd853070_1cee_4fb6_afc0_551a36750e15;

% Combine Variables to statesdot
statesdot = [t_dot_s; v_dot_s; psi_dot_dot_s; beta_dot_s; n_dot_s; xi_dot_s];
j_statesdot = [j_t_dot_s(1,:); j_v_dot_s(1,:); j_psi_dot_dot_s(1,:); j_beta_dot_s(1,:); j_n_dot_s(1,:); j_xi_dot_s(1,:)];

end
