function [out1,out2,out3,out4,out5,out6,out7,out8,out9] = tpbe88c1b2_64dd_4786_862f_71e4428e1e5e(in1val1,in2val1,in3val1,in4val1,in5val1,in6val1)
%TPBE88C1B2_64DD_4786_862F_71E4428E1E5E
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9] = TPBE88C1B2_64DD_4786_862F_71E4428E1E5E(IN1VAL1,IN2VAL1,IN3VAL1,IN4VAL1,IN5VAL1,IN6VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2020 15:12:45

t2 = cos(in3val1);
t3 = cos(in5val1);
t4 = sin(in3val1);
t5 = sin(in5val1);
t6 = in4val1.*in6val1;
t7 = t4.*t5;
t8 = t2.*t3;
t10 = in2val1.*t2.*t5;
t11 = in2val1.*t3.*t4;
t13 = t6-1.0;
t9 = in2val1.*t8;
t12 = in2val1.*t7;
t14 = -t8;
t16 = 1.0./t13;
t18 = t10+t11;
t15 = -t12;
t17 = t16.^2;
t19 = t7+t14;
t21 = t16.*t18;
t20 = t9+t15;
t22 = in6val1.*t21;
t23 = t16.*t20;
out1 = -t23;
if nargout > 1
    out2 = t18;
end
if nargout > 2
    out3 = in1val1+in6val1.*t23;
end
if nargout > 3
    out4 = [0.0,t16.*t19,t21,in6val1.*t17.*t20,t21,in4val1.*t17.*t20];
end
if nargout > 4
    out5 = [0.0,t2.*t5+t3.*t4,t20,0.0,t20,0.0];
end
if nargout > 5
    t24 = -t22;
    out6 = [1.0,-in6val1.*t16.*t19,t24,-in6val1.^2.*t17.*t20,t24,t23-t6.*t17.*t20];
end
if nargout > 6
    out7 = zeros(0,0);
end
if nargout > 7
    out8 = zeros(0,0);
end
if nargout > 8
    out9 = zeros(0,0);
end

end
